name: Build and ping FeaturePeek
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Use node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, and start
      run: |
        npm install
        npm start
      env:
        CI: true
    
    - name: Ping FeaturePeek
      run: bash <(curl -s https://peek.run/ci) -p docker.pkg.github.com//frontend:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}